// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltimateMonopoly.Data;

#nullable disable

namespace UltimateMonopoly.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608100917_EventJsonTable")]
    partial class EventJsonTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JC.Communication.Logging.Models.Email.EmailContentLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("EmailLogId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("HtmlBodyRaw")
                        .HasColumnType("longtext");

                    b.Property<string>("PlainBody")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("EmailLogId")
                        .IsUnique();

                    b.ToTable("EmailContentLogs");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Email.EmailLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Email.EmailRecipientLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailLogId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<int>("RecipientLogType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("EmailLogId");

                    b.ToTable("EmailRecipientLogs");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Email.EmailSentLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("EmailLogId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ServerResponse")
                        .HasColumnType("longtext");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("EmailLogId");

                    b.ToTable("EmailSentLogs");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Messaging.MessageReadLog", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime>("ReadAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("MessageId", "UserId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("MessageReadLogs");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Messaging.ThreadActivityLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ActivityDetails")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("ActivityTimestampUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("ThreadId");

                    b.ToTable("ThreadActivityLogs");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Notifications.NotificationLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("JC.Communication.Messaging.Models.DomainModels.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("varchar(8192)");

                    b.Property<string>("ReplyToMessageId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("RestoredById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("RestoredById");

                    b.HasIndex("ThreadId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("JC.Communication.Messaging.Models.DomainModels.ChatMetadata", b =>
                {
                    b.Property<string>("ThreadId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ColourHex")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ColourRgb")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ImgPath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("RestoredById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("ThreadId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("RestoredById");

                    b.ToTable("ChatMetadata");
                });

            modelBuilder.Entity("JC.Communication.Messaging.Models.DomainModels.ChatParticipant", b =>
                {
                    b.Property<string>("ThreadId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("CanSeeHistory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("LastModifiedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("RestoredById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("ThreadId", "UserId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("RestoredById");

                    b.HasIndex("UserId");

                    b.ToTable("ChatParticipants");
                });

            modelBuilder.Entity("JC.Communication.Messaging.Models.DomainModels.ChatThread", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<bool>("IsDefaultThread")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsGroupThread")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastActivityUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("LastModifiedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RestoredById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("RestoredById");

                    b.ToTable("ChatThreads");
                });

            modelBuilder.Entity("JC.Communication.Messaging.Models.DomainModels.ThreadDeleted", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("RestoredById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("RestoredById");

                    b.HasIndex("ThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("DeletedThreads");
                });

            modelBuilder.Entity("JC.Communication.Notifications.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("varchar(8192)");

                    b.Property<string>("BodyHtml")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RestoredById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UrlLink")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("RestoredById");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("JC.Communication.Notifications.Models.NotificationStyle", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("CustomColourClass")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CustomIconClass")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("RestoredById")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("DeletedById");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("RestoredById");

                    b.ToTable("NotificationStyles");
                });

            modelBuilder.Entity("JC.Core.Models.Auditing.AuditEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("ActionData")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TableName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuditDate");

                    b.HasIndex("TableName");

                    b.HasIndex("UserId");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("JC.Github.Models.IssueComment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("IssueNumber");

                    b.ToTable("IssueComments");
                });

            modelBuilder.Entity("JC.Github.Models.ReportedIssue", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("Closed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob");

                    b.Property<bool>("ReportSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserDisplay")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Closed");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ReportedIssues");
                });

            modelBuilder.Entity("JC.Identity.Models.MultiTenancy.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Domain")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ExpiryDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<uint?>("MaxUsers")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UltimateMonopoly.Data.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("UltimateMonopoly.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarColour")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("AvatarImageName")
                        .HasMaxLength(10240)
                        .HasColumnType("varchar(10240)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastActiveUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<uint>("NumberOfDraws")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("NumberOfLosses")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("NumberOfWins")
                        .HasColumnType("int unsigned");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Boards.BoardSkin", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(10240)
                        .HasColumnType("varchar(10240)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BoardSkins");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Boards.BoardSkinSpace", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<ushort>("Index")
                        .HasColumnType("smallint unsigned");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("PropertySet")
                        .HasColumnType("int");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SpaceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("BoardSkinSpaces");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Boards.SharedBoardSkin", b =>
                {
                    b.Property<string>("BoardSkinId")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("UserId")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BoardSkinId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SharedBoardSkins");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("BoardId")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoundingRule")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("CreatedById", "State");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.GamePlayer", b =>
                {
                    b.Property<string>("GameId")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("UserId")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<ushort?>("Dice1")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("Dice2")
                        .HasColumnType("smallint unsigned");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<ushort>("OrderId")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GameId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "Dice1", "Dice2")
                        .IsUnique();

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.GameSnapshot", b =>
                {
                    b.Property<string>("TurnId")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TurnId");

                    b.HasIndex("GameId");

                    b.ToTable("GameSnapshots");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.GameTurn", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFinalTurn")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("TurnNumber")
                        .HasColumnType("int unsigned");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "TurnNumber");

                    b.HasIndex("GameId", "UserId");

                    b.ToTable("GameTurns");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.GameTurnEvents", b =>
                {
                    b.Property<string>("TurnId")
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TurnId");

                    b.HasIndex("GameId");

                    b.ToTable("GameTurnEvents");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Social.BlockedUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("BlockedUserId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("CreatedById", "BlockedUserId");

                    b.ToTable("BlockedUsers");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Social.Friend", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateRemovedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FriendUserId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FriendUserId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Social.FriendRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ToUserId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Social.ReportedUser", b =>
                {
                    b.Property<string>("BlockedId")
                        .HasMaxLength(38)
                        .HasColumnType("varchar(38)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModifiedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasMaxLength(10240)
                        .HasColumnType("varchar(10240)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<string>("RestoredById")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BlockedId");

                    b.ToTable("ReportedUsers");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Email.EmailContentLog", b =>
                {
                    b.HasOne("JC.Communication.Logging.Models.Email.EmailLog", "EmailLog")
                        .WithOne("EmailContentLog")
                        .HasForeignKey("JC.Communication.Logging.Models.Email.EmailContentLog", "EmailLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailLog");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Email.EmailRecipientLog", b =>
                {
                    b.HasOne("JC.Communication.Logging.Models.Email.EmailLog", "EmailLog")
                        .WithMany("EmailRecipientLogs")
                        .HasForeignKey("EmailLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailLog");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Email.EmailSentLog", b =>
                {
                    b.HasOne("JC.Communication.Logging.Models.Email.EmailLog", "EmailLog")
                        .WithMany("EmailSentLogs")
                        .HasForeignKey("EmailLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailLog");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Messaging.MessageReadLog", b =>
                {
                    b.HasOne("JC.Communication.Messaging.Models.DomainModels.ChatMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Messaging.ThreadActivityLog", b =>
                {
                    b.HasOne("JC.Communication.Messaging.Models.DomainModels.ChatThread", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Notifications.NotificationLog", b =>
                {
                    b.HasOne("JC.Communication.Notifications.Models.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("JC.Communication.Messaging.Models.DomainModels.ChatMessage", b =>
                {
                    b.HasOne("JC.Communication.Messaging.Models.DomainModels.ChatMessage", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JC.Communication.Messaging.Models.DomainModels.ChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplyToMessage");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("JC.Communication.Messaging.Models.DomainModels.ChatMetadata", b =>
                {
                    b.HasOne("JC.Communication.Messaging.Models.DomainModels.ChatThread", "Thread")
                        .WithOne("ChatMetadata")
                        .HasForeignKey("JC.Communication.Messaging.Models.DomainModels.ChatMetadata", "ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("JC.Communication.Messaging.Models.DomainModels.ChatParticipant", b =>
                {
                    b.HasOne("JC.Communication.Messaging.Models.DomainModels.ChatThread", "Thread")
                        .WithMany("Participants")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("JC.Communication.Messaging.Models.DomainModels.ThreadDeleted", b =>
                {
                    b.HasOne("JC.Communication.Messaging.Models.DomainModels.ChatThread", "Thread")
                        .WithMany("UserThreadDeletions")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("JC.Communication.Notifications.Models.NotificationStyle", b =>
                {
                    b.HasOne("JC.Communication.Notifications.Models.Notification", "Notification")
                        .WithOne("Style")
                        .HasForeignKey("JC.Communication.Notifications.Models.NotificationStyle", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("UltimateMonopoly.Data.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UltimateMonopoly.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UltimateMonopoly.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("UltimateMonopoly.Data.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateMonopoly.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UltimateMonopoly.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Boards.BoardSkinSpace", b =>
                {
                    b.HasOne("UltimateMonopoly.Models.DataModels.Boards.BoardSkin", "BoardSkin")
                        .WithMany("Spaces")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardSkin");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Boards.SharedBoardSkin", b =>
                {
                    b.HasOne("UltimateMonopoly.Models.DataModels.Boards.BoardSkin", "BoardSkin")
                        .WithMany("SharedWith")
                        .HasForeignKey("BoardSkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardSkin");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.Game", b =>
                {
                    b.HasOne("UltimateMonopoly.Models.DataModels.Boards.BoardSkin", "BoardSkin")
                        .WithMany()
                        .HasForeignKey("BoardId");

                    b.Navigation("BoardSkin");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.GamePlayer", b =>
                {
                    b.HasOne("UltimateMonopoly.Models.DataModels.Games.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.GameSnapshot", b =>
                {
                    b.HasOne("UltimateMonopoly.Models.DataModels.Games.Game", "Game")
                        .WithMany("Snapshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateMonopoly.Models.DataModels.Games.GameTurn", "Turn")
                        .WithMany()
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.GameTurn", b =>
                {
                    b.HasOne("UltimateMonopoly.Models.DataModels.Games.Game", "Game")
                        .WithMany("Turns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateMonopoly.Models.DataModels.Games.GamePlayer", "Player")
                        .WithMany()
                        .HasForeignKey("GameId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.GameTurnEvents", b =>
                {
                    b.HasOne("UltimateMonopoly.Models.DataModels.Games.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateMonopoly.Models.DataModels.Games.GameTurn", "GameTurn")
                        .WithMany()
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameTurn");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Social.ReportedUser", b =>
                {
                    b.HasOne("UltimateMonopoly.Models.DataModels.Social.BlockedUser", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedUser");
                });

            modelBuilder.Entity("JC.Communication.Logging.Models.Email.EmailLog", b =>
                {
                    b.Navigation("EmailContentLog");

                    b.Navigation("EmailRecipientLogs");

                    b.Navigation("EmailSentLogs");
                });

            modelBuilder.Entity("JC.Communication.Messaging.Models.DomainModels.ChatThread", b =>
                {
                    b.Navigation("ChatMetadata");

                    b.Navigation("Messages");

                    b.Navigation("Participants");

                    b.Navigation("UserThreadDeletions");
                });

            modelBuilder.Entity("JC.Communication.Notifications.Models.Notification", b =>
                {
                    b.Navigation("Style");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Boards.BoardSkin", b =>
                {
                    b.Navigation("SharedWith");

                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("UltimateMonopoly.Models.DataModels.Games.Game", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Snapshots");

                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
